[tool.poetry]
name = "gen3"
version = "3.1.0"
description = "Gen3 3.1"
authors = ["Fantix King <fantix@uchicago.edu>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
