name: yarn build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@preview
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/web/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: yarn build
      run: |
        npm install -g yarn
        cd web
        yarn install
        yarn build
      env:
        CI: true
    - uses: actions/upload-artifact@master
      with:
        name: web build output
        path: web/dist
